### ISSUE TITLE
Add helper function to setup Mozilla repository

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-automation-tools#26]
Mike has started the work to create a Mozilla Gradle plugin.

Let's add a helper to setup the Mozilla repository - so that we can just do:

```Groovy
repositories {
    mozilla()
}
```

**Comment by mcomella** [comment]
Turns out this is actually non-trivial. Google's repository is actually embedded in the gradle source code, not applied by their gradle plugin, so we can't see what they do. I believe a `mozilla()` shortcut can be enabled by:
- Language level functionality (e.g. reflection) but it's unclear how added code gets exposed to the project applying the gradle plugin
- The Gradle APIs: this is the correct way to do it but these are confusing and not well documented

### Language level
The simplest way appears to be to use Groovy meta classes like:
https://github.com/Ullink/gradle-repositories-plugin/blob/2496879e90db9463524fd6d66330b8de19860383/src/main/groovy/com/ullink/RepositoriesPlugin.groovy#L50-L54

However, I don't know how to mix groovy and kotlin code, nor do I know that these would be exposed to the non-groovy build scripts (which we're probably trying to move away from).

I tried using Kotlin extension functions (on RepositoryHandler) but I'm not sure how these are exposed to Groovy. Sample with a top-level Kotlin function that returns the appropriate object.

### Gradle APIs
`project.repositories` is a `RepositoryHandler` which I think implements [`ArtifactRepositoryContainer`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ArtifactRepositoryContainer.html). I tried using the add methods, but it doesn't seem to get exposed to the project. It's unclear whether `add` is supposed to configure the artifact for the repository or just add it to a collection (i.e. no side effects).

[This SO post](https://stackoverflow.com/q/44163334) writing a Java plugin seems to get the closest to what we want but I was unable to get that working quite right. There's also [this post](https://stackoverflow.com/q/45422416) but that was also unhelpful.

## Alternatives
There are some conceptually simpler things we can try to do:
- Provide a URL constant so users do `maven { url = MOZILLA_MAVEN }` instead of `mozilla()`
- Automatically apply it to all projects that apply the plugin: I was unable to get this working either. This is conceptually simpler because you don't need to figure out how to add items to the gradle DSL: you can just call the APIs directly.

**Overall, this functionality seems like a small win for a lot of time so I don't think it's worth it.**

Side note: I feel like this might be quicker to develop if I could [write it in a test harness](https://guides.gradle.org/testing-gradle-plugins/#manual-tests) rather than having to publish to a local maven repository and modify another project to work on it.
