### ISSUE TITLE
Make tools available through single command?

### ISSUE THREAD

**Issue by pocmo** [mozilla-mobile/android-automation-tools#9]
Like we use "mach" in mozilla-central.

**Comment by mcomella** [comment]
We already have one: `/.gradlew`! :) If we put our tooling in gradle, we can write our tooling in kotlin (since it can compile and run the tools) which we're all more familiar with. Since all the code is imported into the same top-level gradle project, we can also share helper functions and utilities, which is harder to encourage with separate python scripts.

If we prefer to write python at times (e.g. for the l10n team), it's easy to call out to shell tasks from gradle too:
```groovy
task getLocales(type: Exec) {
    commandLine 'bash' '-c' './tools/get_locales.py'
}
```

fwiw, PR #25 adds a top-level gradle project to this repository so you can see what that might look like.

**Comment by mcomella** [comment]
Do you agree? Disagree? Should we leave this issue open? :)

**Comment by pocmo** [comment]
Yeah, I think that's a great idea.

For Python: The telemetry team was experimenting with a Python Gradle plugin that can setup a plugin-local Python environment to run some scripts - so that no Python installation and setup is needed.

**Comment by mcomella** [comment]
If it's helpful, I did something similar for npm and danger: https://github.com/mcomella/firefox-tv/commit/eb7b4ca6ff0ccff81fe4e7bdf5213513cf427913#diff-507bae2efd9f3286a526cf3b992aa818R26
